name: Build & Test Medan CLI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout medan-cli
        uses: actions/checkout@v4
        with:
          path: medan-cli

      - name: Checkout medan-engine
        uses: actions/checkout@v4
        with:
          repository: Medan-org/medan-engine
          path: medan-engine

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd medan-cli
          npm install

      - name: Build Medan CLI
        run: |
          cd medan-cli
          npm run build

      - name: Test: Medan CLI help command
        run: |
          cd medan-cli
          node dist/index.js medan --help

      - name: Test: Medan identity command
        run: |
          cd medan-cli
          node dist/index.js medan

      - name: Test: Nano command
        run: |
          cd medan-cli
          node dist/index.js nano test.txt

      - name: Test: Curl command
        run: |
          cd medan-cli
          node dist/index.js curl https://example.com
